services:
  # mongo:
  #   container_name: mongo
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: devcon
      POSTGRES_DB: payments
    volumes:
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  processor:
    container_name: processor
    build: ./processor
    ports:
      - "2024:2024"
    depends_on:
      - postgres
      - redis

  # payments:
  #   container_name: payments
  #   build: ./payments
  #   ports:
  #     - "2023:2023"
  #   depends_on:
  #     - mongo
  #     - redis

  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "2025:2025"
    depends_on:
      #- payments
      - processor
      - redis
