services:
  # Mongo Database
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./infrastructure/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # Postgres Database
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: devcon
      POSTGRES_DB: payments
    volumes:
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  # Redis Cluster for Federation
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  # .NET 9 Payments API Service
  payments-api:
    build:
      context: .
      dockerfile: payments/Payments.API/Dockerfile
    ports:
      - "2022:80"
    depends_on:
      - mongo
      - redis

  # .NET 9 Payments UI (Blazor)
  payments-ui:
    build:
      context: .
      dockerfile: payments/Payments.UI/Dockerfile
    ports:
      - "2023:80"
    depends_on:
      - payments-api

  # Python API Service
  processor:
    container_name: processor
    build: ./processor
    ports:
      - "2024:2024"
    depends_on:
      - postgres
      - redis

  # Node.js/Typescript Gateway
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - "2025:2025"
    environment:
      - NODE_ENV=development
    depends_on:
      - payments-api
      - processor
      - redis
      - postgres
      - mongo
